services:
  api:
    build: ./
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mariadb:12.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
