// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fox-storage/controller"
	"fox-storage/db"
	"fox-storage/handler"
	"fox-storage/repository"
	"fox-storage/router"
	"fox-storage/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeRouter() *gin.Engine {
	gormDB := db.InitDB()
	itemRepository := repository.NewItemRepository(gormDB)
	itemService := service.NewItemService(itemRepository)
	itemController := controller.NewItemController(itemService)
	itemHandler := handler.NewItemHandler(itemController)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	userHandler := handler.NewUserHandler(userController)
	engine := router.NewRouter(itemHandler, userHandler)
	return engine
}
